name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
    - name: Build the Preprocess image
<<<<<<< HEAD
      run: docker build ./boston_housing/preprocess_data --tag chowk1109/boston_pipeline_preprocessing
=======
      run: docker build ./boston_housing/preprocess_data --tag chowk1109/boston_pipeline_preprocessing
    - name: Push the Preprocess image
      run: docker push chowk1109/boston_pipeline_preprocessing
>>>>>>> merge
